-- Create custom enums
CREATE TYPE user_role AS ENUM ('corretor', 'gestor');
CREATE TYPE origem_type AS ENUM ('RELACIONAMENTO', 'PATROCINADO', 'CORRETOR_EXTERNO', 'CORRETOR_INTERNO', 'PORTAL');
CREATE TYPE investimento_type AS ENUM ('PORTAL', 'PATROCINADO', 'CURSO', 'NETWORKING', 'PRESENTE_CLIENTE', 'BRINDE', 'OUTRO');
